notifications:
  commits:              commits@pekko.apache.org
  issues:               notifications@pekko.apache.org
  pullrequests:         notifications@pekko.apache.org 

staging:
  profile: ~
  whoami: asf-staging

publish:
  profile: ~
  whoami: asf-site

